project:
  title: "Bruno Montezano | Psicólogo & Analista de Dados"
  output-dir: ./docs

website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    right:
      - href: ../
        text: 🇧🇷
      - href: ../en
        text: 🇺🇸

lang: pt-br

format:
  html:
    theme: litera
    highlight-style: breeze
    css: styles.css
    toc: true
