project:
  output-dir: ./docs

website:
  title: "Bruno Montezano"
  description: "Psicólogo & Analista de Dados"
  search: false
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    right:
      - href: ../
        text: 🇧🇷
      - href: ../en
        text: 🇺🇸

lang: pt-br

format:
  html:
    theme:
      - litera
      - custom.scss
    highlight-style: breeze
    mainfont: Lato
    toc: true
