project:
  output-dir: ./docs

website:
  title: "Bruno Montezano"
  description: "Psicólogo & Analista de Dados"
  search: false
  favicon: assets/favicon/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    right:
      - href: ../
        text: 🇧🇷
      - href: ../en
        text: 🇺🇸

lang: pt-br

format:
  html:
    theme:
      - litera
      - assets/css/custom.scss
    highlight-style: breeze
    mainfont: Lato
    description-meta: Site do pesquisador Bruno Montezano, que trabalha com técnicas computacionais aplicadas à saúde mental.
    author-meta: Bruno Braga Montezano
    pagetitle: Bruno Montezano
    keywords: [estatística, pesquisa, programação, saúde, doutorado, mestrado, psiquiatria, psicologia]
    toc: true
